### ISSUE TITLE
Does website need to be rebuilt?

### ISSUE THREAD

**Issue by rpruim** [ggplot2-exts/gallery#51] opened 2018-08-27 15:57 UTC
The ggformula package was submitted quite some time ago and the pull request accepted, but it still doesn't appear online.  Was there an error in that submission?  Does the website simply need to be rebuilt?  Is there some other problem?

**Comment by rpruim** [comment] 2018-08-27 15:58
Here is the PR: https://github.com/ggplot2-exts/gallery/pull/47

**Comment by yutannihilation** [comment] 2019-01-30 04:27
The problem is fixed now!

https://github.com/ggplot2-exts/gallery/pull/54

**Comment by rpruim** [comment] 2019-01-30 05:14
thanks!

**Comment by Emaasit** [comment] 2019-01-30 05:48
Thanks @yutannihilation

**Closed as completed by Emaasit** 2019-01-30 05:48 UTC
